// Generated by CoffeeScript 1.6.2
(function() {
  var Question;

  Question = (function() {
    function Question() {
      this.questionIsStarted = false;
      this.nbVote = 0;
      this.a_possibleAnswers = [];
      this.a_userAnswersCount = [];
      this.a_userName = [];
    }

    Question.prototype.startListening = function() {
      var _this = this;

      return $('#list').bind('DOMNodeInserted', function(e) {
        var elem, insertValue, pos, user;

        elem = e.target;
        insertValue = elem.innerText.toLowerCase();
        user = elem.dataset.sender;
        if ((pos = $.inArray(insertValue, _this.a_possibleAnswers)) >= 0 && $.inArray(user, _this.a_userName) === -1) {
          _this.a_userAnswersCount[pos]++;
          $(".q_" + pos).next().text(_this.a_userAnswersCount[pos]);
          return _this.a_userName.push(user);
        }
      });
    };

    Question.prototype.stopListening = function() {
      return $('#list').unbind('DOMNodeInserted');
    };

    Question.prototype.initUIListener = function() {
      var _this = this;

      $('#btn-start').on('click', function(e, elem) {
        if (_this.a_possibleAnswers.length > 0) {
          _this.questionIsStarted = !_this.questionIsStarted;
          if (_this.questionIsStarted) {
            _this.startListening();
            $(e.currentTarget).removeClass("btn-danger").addClass("btn-success");
            return $(e.currentTarget).find("span.value").text("stop");
          } else {
            _this.stopListening();
            $(e.currentTarget).addClass("btn-danger").removeClass("btn-success");
            return $(e.currentTarget).find("span.value").text("start");
          }
        } else {
          return alert('You have to define some answers first.');
        }
      });
      $('#change-question').editable(function(value, settings) {
        return value;
      }, {
        event: 'click',
        cancel: 'Cancel',
        submit: 'OK',
        indiciator: 'Saving..'
      });
      $('form#add-answer').on('submit', function(e) {
        var num, value;

        value = $('input#add-answer-value').val();
        num = _this.a_possibleAnswers.length;
        $('#answers-list tbody').append("<tr><td class=\"q_" + num + "\">" + value + "</td><td class=\"count\">0</td><td class=\"delete\"><i class=\"icon-remove\"></i></td></tr>");
        _this.a_possibleAnswers.push(value.toLowerCase());
        _this.a_userAnswersCount.push(0);
        $("input#add-answer-value").val("");
        return false;
      });
      return $('table#answers-list i').on('click', function() {
        return console.log('delete');
      });
    };

    Question.prototype.initUI = function() {
      $('body').prepend('<div id="twitch-question-ui"></div>');
      return $('#twitch-question-ui').append("<p id=\"btn-start\" style=\"color:" + colorInactive + ">Ask question !</p>");
    };

    return Question;

  })();

  $(document).ready(function() {
    var q;

    $('form#msg').submit(function(e) {
      var pseudo, val;

      val = $("input#test").val();
      pseudo = $("input#pseudo").val();
      $("#list").append("<li data-sender=\"" + pseudo + "\">" + val + "</li>");
      return false;
    });
    q = new Question();
    return q.initUIListener();
  });

}).call(this);
